name-template: 'v$RESOLVED_VERSION 🚀'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '✨ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'refactor'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
      - 'npm'
      - 'pip'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'bugfix'
      - 'fix'
      - 'documentation'
      - 'docs'
      - 'chore'
      - 'maintenance'
      - 'refactor'
      - 'dependencies'
  default: patch

template: |
  ## 🚀 What's New in v$RESOLVED_VERSION

  $CHANGES

  ## 👨‍💻 Contributors

  $CONTRIBUTORS

  ## 📦 Installation

  ```bash
  # Install via npm
  npm install elements-of-prompt-engineering

  # Or via pip
  pip install elements-prompt-engineering
  ```

  ## 📚 Documentation

  For full documentation, visit our [GitHub repository](https://github.com/timothywarner/elements).

  ## 🔗 Links

  - [Course Materials](/docs)
  - [Sample Prompts](/scripts/prompt-templates)
  - [Debugging Tools](/src)

exclude-labels:
  - 'skip-changelog'
